export {
  // Namespaces and Types
  RemoteData,
  NotAsked,
  Loading,
  Success,
  Failure,
  // Constructors
  notAsked,
  loading,
  success,
  of,
  failure,
  failureData,
  // Typeguards
  isNotAsked,
  isLoading,
  isSuccess,
  isFailure,
  isCompleted,
  // Conversions
  fromOption,
  fromResult,
  toOption,
  toResult,
  coerceNotAsked,
  coerceLoading,
  coerceSuccess,
  coerceFailure,
  // Operations
  ifNotAsked,
  ifLoading,
  ifSuccess,
  ifFailure,
  orDefault,
  orThrow,
  match,
  consolidate,
  encase,
  encaseWithData,
  encasePromise,
  encasePromiseWithData,
};

import { RemoteData } from "./namespace";
import { NotAsked } from "./NotAsked/namespace";
import { Loading } from "./Loading/namespace";
import { Success } from "./Success/namespace";
import { Failure } from "./Failure/namespace";
const {
  notAsked,
  loading,
  success,
  failure,
  failureData,
  of,
  isNotAsked,
  isLoading,
  isSuccess,
  isFailure,
  isCompleted,
  fromOption,
  fromResult,
  toOption,
  toResult,
  coerceNotAsked,
  coerceLoading,
  coerceSuccess,
  coerceFailure,
  ifNotAsked,
  ifLoading,
  ifSuccess,
  ifFailure,
  orDefault,
  orThrow,
  match,
  consolidate,
  encase,
  encaseWithData,
  encasePromise,
  encasePromiseWithData,
} = RemoteData;
